### ISSUE TITLE
SCons compilation fails on Debian 8 Jessie

### ISSUE THREAD

**Issue by ThibaultLemaire** [freelan-developers/freelan#116]
After following [build instructions](https://github.com/Naughtylus/freelan/blob/master/BUILD.md), scons fails to compile on debian 8.6 with the following error:

```
scons: Reading SConscript files ...
AttributeError: 'NoneType' object has no attribute 'rfind':
  File "/home/naughtylus/Projects/public/cpp/freelan/SConstruct", line 151:
    env = FreelanEnvironment(mode='release', prefix=prefix)
  File "/home/naughtylus/Projects/public/cpp/freelan/SConstruct", line 78:
    if os.path.basename(self['CXX']) == 'clang++':
  File "/usr/lib/python2.7/posixpath.py", line 121:
    i = p.rfind('/') + 1
```
Tested with current [HEAD](https://github.com/freelan-developers/freelan/tree/43062cd97e869df3334c72abf0f99797ff20e539), and tags [2.0](https://github.com/freelan-developers/freelan/tree/2.0) and [debian/2.0-1](https://github.com/freelan-developers/freelan/tree/debian/2.0-1)

------------------

I know my way around python, but am new to freelan. Will try to investigate.

**Comment by Naughtylus** [comment]
Looks like I'm missing the compilation flags in my environment...

Could it be because I didn't use teapot? I thought this was OK since I could install the dependencies via apt.

**Comment by Naughtylus** [comment]
Alright, I'm an idiot. **I was just missing the g++**.

I reinstalled my machine fairly recently and forgot I hadn't installed it.

So, for idiots like myself who forget they need a compiler to compile source code, should we :

1. Add `g++` to the list of dependencies in the [build instructions](https://github.com/Naughtylus/freelan/blob/master/BUILD.md) ?

2. Add a compilation warning to the SConstruct file (something like "CXX variable not found, are you missing a compiler?") ?

I can make a merge request, just tell me 'yes' or 'no' for 1. and 2. :)

**Comment by ereOn** [comment]
@Naughtylus Glad you solved it !

You are not an idiot: idiots usually don't try when it doesn't work the first time ;) Also, I made the exact same mistake last week so at least you are not alone !

For 1. that seems like a good idea. I wrongly assumed that only people that play with C++ everyday would try to compile FreeLAN from sources, but that's obviously a wrong assertion.

I'm not sure about 2. : I don't know if SConstruct allows that easily. The SConstruct files are not imperative but rather declarative (well the Python code is imperative but the real work afterwards is done in a "smart" way from the various declarations). I would not be sure where to put such a check that would be sensible.

If you do know though, I'll happily consider it. So yes, be free to make a Pull Request !

Thanks !

**Comment by Naughtylus** [comment]
Well yeah, freelan being only available in the Stretch repository (currently testing), I can't get any packages for my Jessie machine.

So I decided to compile directly from source (and I believe I won't be the only one in this case, hence the idea of an explicit error).

**Comment by ereOn** [comment]
@Naughtylus Just to make a follow up: is this still an active issue ?

If not, can we close it ?

**Comment by Naughtylus** [comment]
I was planning on closing it once the merge request is closed so anyone having the same issue in the meantime could stumble upon this issue and hopefully fix it by themselves, but I guess you can close it now if you want.

**Comment by leggewie** [comment]
No need to explicitly depend on g++ as that is pulled in via the package build-essential.

Use "dpkg-checkbuilddeps" in the source directory with debian directory to find out if you are missing a build-time dependency.

Closing as invalid, but thank you for the discussion.
